Algoritmo "Lista 1 Exercício 3"
// Disciplina  : Algoritmos
// Professor   : Douglas Dutra
// Descrição   : Antecessor e Sucessor
// Autor(a)    : Pedro Henrique dos Santos
// Data atual  : 04/03/2026
Var
// Seção de Declarações das variáveis
   n, x : real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreval("Insira um número:")
   leia(n)
   x <- n-1
   escreval("Antecessor: ", x)
   x <- n+1
   escreval("Sucessor: ", x)
Fimalgoritmo