Algoritmo "Lista 1 Exercício 1"
// Disciplina  : Algoritmos
// Professor   : Douglas Dutra
// Descrição   : Soma e produto de dois números
// Autor(a)    : Pedro Henrique dos Santos
// Data atual  : 04/03/2026
Var
// Seção de Declarações das variáveis 
   x, y, soma, produto : real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   ESCREVAL("Digite o 1º Número: ")
   LEIA(x)
   ESCREVAL("Digite o 2º Número: ")
   LEIA(y)
   SOMA <- x + y
   PRODUTO <- x / y
   ESCREVAL("Soma: ", SOMA)
   ESCREVAL("Produto: ", PRODUTO)
Fimalgoritmo