Algoritmo "LISTA 2 EXERCICIO 5"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 24/03/2026
Var
   v,w,x,y,z: inteiro
   numeros: vetor[0..4] de inteiro
   media: real


Inicio
      escreval("Insira primeiro número: ")
      leia(v)
      vetor[0] <- v
      escreval("Insira segundo número: ")
      leia(w)
      vetor[1] <- w
      escreval("Insira terceiro número: ")
      leia(x)
      vetor[2] <- x
      escreval("Insira quarto número: ")
      leia(y)
      vetor[3] <- y
      escreval("Insira quinto número: ")
      leia(z)
      vetor[4] <- z
      media <- (v+w+x+y+z)/5
      para num de 1 ate 5 faca

Fimalgoritmo