Algoritmo "LISTA 2 EXERCICIO 1"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 18/03/2026
Var
   x: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreval("insira numero")
   leia(x)
   se (x > 0) ou (x <= 9) entao
        escreval("O valor está na faixa permitida")
   senao
        escreval("O valor está fora da faixa permitida")
   fimse

Fimalgoritmo