Algoritmo "Lista 1 Exercício 4"
// Disciplina  : Algoritmos
// Professor   : Douglas Dutra
// Descrição   : Conversão de temperatura
// Autor(a)    : Pedro Henrique dos Santos
// Data atual  : 04/03/2026
Var
// Seção de Declarações das variáveis
   c, f : real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
   escreval("Insira a temperatura em celsius:")
   leia(c)
   f <- (C*9/5)+32
   escreval("Temperatura em fahrenheit: ", f)
Fimalgoritmo